version: "3.7"
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    volumes:
      - /home/charlie/config/plextraktsync:/config
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=1000
      - PGID=1000
      - PMM_CONFIG=/config/config.yml
    volumes:
      - /home/charlie/config/pmm:/config
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=jellyfin.charlie-cloud.com #optional
    volumes:
      - /home/charlie/config/jellyfin:/config
      - /home/charlie/data/media/tv:/data/tvshows
      - /home/charlie/data/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1901:1900/udp #optional
  router:
    image: envoyproxy/envoy:v1.19.1
    container_name: envoy
    ports:
    - 192.168.86.36:80:80   # private-http
    - 8888:79
      #- 136.49.216.161:80:81   # public-http
    - 443:443 # public-https
    - 9901:9901
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    - ./certs:/certs
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    ports:
    - 3005:3005   # Plex Companion
    - 8324:8324   # Roku via Plex Companion
    - 32400:32400 # UI
    - 1900:1900/udp   # Plex DLNA Server
    - 32410:32410/udp # Network Discovery
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
    - 33400:33400 # WebTools
    volumes:
    - /home/charlie/config/plex:/config
    - /home/charlie/data/media/tv:/data/tvshows
    - /home/charlie/data/media/movies:/data/movies
    - /home/charlie/data/media/books:/data/books
    - /home/charlie/data/plex/transcode:/transcode
    environment:
    - VERSION=docker
    # - PLEX_CLAIM=claim-red-act-ed
    - PUID=1000
    - GUID=1000
  readarr:
    image: linuxserver/readarr:0.1.1-nightly
    container_name: readarr
    ports:
    - 8787:8787
    volumes:
    - /home/charlie/config/readarr:/config
    - /home/charlie/data/media/books:/books
    - /home/charlie/data/qbittorrent/downloads:/downloads
    environment:
    - PUID=1000
    - GUID=1000
  auto-m4b:
    image: seanap/auto-m4b
    container_name: auto-m4b
    volumes:
      - /home/charlie/config/auto-m4b:/config
      - /home/charlie/data/media/books:/temp
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
    - /home/charlie/config/sonarr:/config
    - /home/charlie/data/media/tv:/tv
    - /home/charlie/data/qbittorrent/downloads:/downloads
    environment:
    - PUID=1000
    - GUID=1000
    ports:
    - 8989:8989
    logging:
      driver: loki
      options:
        loki-url: "https://${LOKI_CRED:?err}@logs-prod3.grafana.net/api/prom/push"
        loki-retries: "5"
        loki-batch-size: "10"
        loki-pipeline-stages: |
          - replace:
              expression: 'X-Plex-Token=(\w+)'
              replace: '******'
          - regex:
              expression: '\[(?P<level>\w+)\]'
          - labels:
              level:
  radarr:
    image: linuxserver/radarr:4.2.0-nightly # For plex watchlist integration. 
    container_name: radarr
    volumes:
    - /home/charlie/config/radarr:/config
    - /home/charlie/data/media/movies:/movies
    - /home/charlie/data/qbittorrent/downloads:/downloads
    environment:
    - PUID=1000
    - GUID=1000
    ports:
    - 7878:7878
    logging:
      driver: loki
      options:
        loki-url: "https://${LOKI_CRED:?err}@logs-prod3.grafana.net/api/prom/push"
        loki-retries: "5"
        loki-batch-size: "10"
        loki-pipeline-stages: |
          - replace:
              expression: 'X-Plex-Token=(\w+)'
              replace: '******'
          - regex:
              expression: '\[(?P<level>\w+)\]'
          - labels:
              level:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
    - /home/charlie/config/bazarr:/config
    - /home/charlie/data/media/movies:/movies
    - /home/charlie/data/media/tv:/tv
    environment:
    - PUID=1000
    - GUID=1000
    ports:
    - 6767:6767
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/charlie/config/overseerr:/config
    ports:
      - 5055:5055
  ombi:
    image: linuxserver/ombi:4.15.4-development #4.14.1-development # latest
    container_name: ombi
    volumes:
    - /home/charlie/config/ombi:/config
    ports:
    - 3579:3579
    logging:
      driver: loki
      options:
        loki-url: "https://${LOKI_CRED:?err}@logs-prod3.grafana.net/api/prom/push"
  qbittorrent:
    image: dyonr/qbittorrentvpn # linuxserver/qbittorrent:latest
    container_name: qbittorrent
    # network_mode: "service:vpn"
    ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
    volumes:
    - /home/charlie/data/qbittorrent/downloads:/downloads
    - /home/charlie/config/qbittorrent:/config
    environment:
    - WEBUI_PORT=8080
    - PUID=1000
    - GUID=1000
    # For VPN
    - LAN_NETWORK=192.168.0.0/24
    env_file:
    - vpn.env
    privileged: true
    devices:
    - /dev/net/tun
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    ports:
    - 9117:9117
    volumes:
    - /home/charlie/config/jackett:/config
    - /home/charlie/data/jackett/downloads:/downloads
    environment:
    - PUID=1000
    - GUID=1000
  jackett-private:
    image: linuxserver/jackett:latest
    container_name: jackett-private
    ports:
    - 9118:9117
    volumes:
    - /home/charlie/config/jackett-private:/configs
    - /home/charlie/data/jackett-private/downloads:/downloads
    environment:
    - PUID=1000
    - GUID=1000
  vpn:
    image: thrnz/docker-wireguard-pia:latest
    container_name: vpn
    environment:
    - LOC=us_south_west
    - USER=${PIA_USER:?err}
    - PASS=${PIA_PASS:?err}
    cap_add:
    - net_admin
      # ports:
      #- 8080:8080     # qbittorrent Web UI
      #- 6881:6881     # qbittorrent
      #- 6881:6881/udp # qbittorrent
  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    ports:
    - 8181:8181
    volumes:
    - /home/charlie/config/tautulli:/config
    environment:
    - PUID=1000
    - GUID=1000
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    ports:
    - 8081:80
    volumes:
    - /home/charlie/config/organizr:/config
    environment:
    - PUID=1000
    - GUID=1000
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    init: true
    user: 1000:1000
    volumes:
      - /home/charlie/config/recyclarr:/config
    environment:
      - TZ=America/Santiago
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
    - 8191:8191
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
    - /home/charlie/config/homeassistant:/config
    - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    volumes:
    - /home/charlie/config/homebridge:/homebridge
    environment:
    - HOMEBRIDGE_CONFIG_UI=1
    - HOMEBRIDGE_CONFIG_UI_PORT=8581
    ports:
    - 8581:8581
